language: cpp
compiler:
  - clang
  - gcc
before_install:
 - echo "yes" | sudo apt-add-repository ppa:zoogie/sdl2-snapshots
 - sudo apt-get update -qq
 - sudo apt-get install libsdl2-dev libglib2.0-dev libopenal-dev gettext libfreetype6-dev libxi-dev libpng12-dev zlib1g-dev libmpeg2-4-dev zip
script: ./bootstrap.sh && ./configure && make distcheck

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "g2yI8YRAL0kcKpFC4e3Bd4U5OePFRz+wXc2Ji0XkG69W66/WJ2KU03NsBRBlAxre6HccXltMl0Zq52ahg3j2c5INASTon68SRT9VIPFiKKXquM1L218hWnyGv6UPHdZldR72s9oiu3dBznIuZFKxsdIjlHW77dmJYJbxFKBkXBo="

addons:
  coverity_scan:
    project:
      name: "FrodeSolheim/fs-uae"
      description: "Build submitted via Travis CI"
    notification_email: frode-code@fengestad.no
    build_command_prepend: "./bootstrap.sh; ./configure;"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
